
services:
  mysql:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: 1234        # รหัสผ่าน root
      MYSQL_DATABASE: roomq               # ชื่อ database เริ่มต้น
      MYSQL_USER: sql                      # ผู้ใช้ใหม่
      MYSQL_PASSWORD: 1234               # รหัสผ่านของผู้ใช้ใหม่
    ports:
      - "3333:3306"                             # พอร์ต MySQL
    volumes:
      - mysql_data:/var/lib/mysql             # เก็บข้อมูลไว้ถาวรในโฟลเดอร์ host
      - ./backend/init_db:/docker-entrypoint-initdb.d   # ⭐ auto run SQL ที่นี่
    command: []   # ไม่ต้องใส่อะไร ปล่อย default
    networks:
      - q_net


  phpmyadmin:
  
    image: phpmyadmin:latest
    container_name: phpmyadmin2
    ports:
      - "8080:80"                      # เปิดหน้าเว็บ phpMyAdmin ผ่าน http://localhost:8080
    environment:
      PMA_HOST: mysql                  # ชื่อ service ของ MySQL (ต้องตรงกับด้านบน)
      PMA_USER: root
      PMA_PASSWORD: 1234
      UPLOAD_LIMIT: 64M
    depends_on:
      - mysql   
    networks:
      - q_net

  backend:
    build: ./backend
    image: registry-ui.vecskill.ovec/my-backend:latest  # ใช้สำหรับ production
    ports:
      - "81:80" 
    environment:
      PORT: 80
      ALLOW_ORIGINS: http://localhost:3000,192.168.100.102:3000
      JWT_SECRET: secret 
      JWT_REFRESH_SECRET: refresh_secret 
      ROOT_USERNAME: admin
      ROOT_PASSWORD: 1234
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: roomq
      MYSQL_USERNAME: sql
      MYSQL_PASSWORD: 1234
    volumes:
      - ./backend/files:/files
    profiles:
      - backend       # ถ้าเรียก profile backend จะ build
      - production    # ถ้าเรียก profile production จะใช้ image จาก registry
    networks:
      - q_net

  frontend:
    build: ./frontend
    image: registry-ui.vecskill.ovec/my-frontend:latest  # ใช้สำหรับ production
    ports:
      - "3000:3000" 
    environment:
      NUXT_PUBLIC_API: http://192.168.100.102:81
      NODE_OPTIONS: "--max-old-space-size=4096"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    profiles:
      - production    # ถ้าเรียก profile production จะใช้ image จาก registry
    networks:
      - q_net

volumes:
  mysql_data:

networks:
  q_net:
    driver: bridge